### ISSUE TITLE
Link lake.gid to location.waterBodyID with constraint

### ISSUE THREAD

**Issue by JakobMiksch** [NINAnor/NOFA#31]
Do we need to link the lake and the location table with constraint?

**Comment by andersfi** [comment]
I think there should be a constraint between the location table and the waterbody table (fk waterBodyID) so that all locations are linked to a waterbody. This waterbody may either be a lake, stream or other waterbody. i.e. not an explicit constraint to the lake table itself, but to the parent table (waterbody)

**Comment by ninsbl** [comment]
Due to table inheritance, I dont think this is possible...

**Comment by ninsbl** [comment]
Now I just gave it a try:
```
ALTER TABLE nofa.location
    ADD CONSTRAINT "location_fk_waterBodyID" FOREIGN KEY ("waterBodyID")
    REFERENCES nofa."waterBody" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;
```
But it ends in an error message:
```
ERROR:  insert or update on table "location" violates foreign key constraint "location_fk_waterBodyID"
DETAIL:  Key (waterBodyID)=(9858) is not present in table "waterBody".
```
However:
```
SELECT * FROM nofa."waterBody" WHERE id = 9858
```
returns a row.
So, this foreign key does not seem possible...
